

set_property IOSTANDARD LVCMOS18 [get_ports clk]


set_property PACKAGE_PIN W7 [get_ports {ssDisp[0]}]
set_property PACKAGE_PIN W6 [get_ports {ssDisp[1]}]
set_property PACKAGE_PIN U8 [get_ports {ssDisp[2]}]
set_property PACKAGE_PIN V8 [get_ports {ssDisp[3]}]
set_property PACKAGE_PIN U5 [get_ports {ssDisp[4]}]
set_property PACKAGE_PIN V5 [get_ports {ssDisp[5]}]
set_property PACKAGE_PIN U7 [get_ports {ssDisp[6]}]
set_property PACKAGE_PIN W4 [get_ports {reg_score[0]}]
set_property PACKAGE_PIN V4 [get_ports {reg_score[1]}]

set_property PACKAGE_PIN L1 [get_ports {led[0]}]
set_property PACKAGE_PIN P1 [get_ports {led[1]}]
set_property PACKAGE_PIN N3 [get_ports {led[2]}]
set_property PACKAGE_PIN P3 [get_ports {led[3]}]
set_property PACKAGE_PIN U3 [get_ports {led[4]}]
set_property PACKAGE_PIN W3 [get_ports {led[5]}]
set_property PACKAGE_PIN V3 [get_ports {led[6]}]
set_property PACKAGE_PIN V13 [get_ports {led[7]}]
set_property PACKAGE_PIN V14 [get_ports {led[8]}]
set_property PACKAGE_PIN U14 [get_ports {led[9]}]

set_property PACKAGE_PIN U18 [get_ports reset]

set_property PACKAGE_PIN W4 [get_ports {reg_score[0]}]
set_property PACKAGE_PIN V4 [get_ports {reg_score[1]}]
set_property PACKAGE_PIN R2 [get_ports {switch[0]}]
set_property PACKAGE_PIN T1 [get_ports {switch[1]}]
set_property PACKAGE_PIN U1 [get_ports {switch[2]}]
set_property PACKAGE_PIN W2 [get_ports {switch[3]}]
set_property PACKAGE_PIN R3 [get_ports {switch[4]}]
set_property PACKAGE_PIN T2 [get_ports {switch[5]}]
set_property PACKAGE_PIN T3 [get_ports {switch[6]}]
set_property PACKAGE_PIN V2 [get_ports {switch[7]}]
set_property PACKAGE_PIN W13 [get_ports {switch[8]}]
set_property PACKAGE_PIN W14 [get_ports {switch[9]}]
set_property PACKAGE_PIN W5 [get_ports clk]

set_property IOSTANDARD LVCMOS18 [get_ports {led[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {led[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {led[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {led[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {led[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {led[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {led[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {led[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {led[8]}]
set_property IOSTANDARD LVCMOS18 [get_ports {led[9]}]

set_property IOSTANDARD LVCMOS18 [get_ports {reg_score[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {reg_score[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {switch[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {switch[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {switch[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {switch[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {switch[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {switch[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {switch[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {switch[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {switch[8]}]
set_property IOSTANDARD LVCMOS18 [get_ports {switch[9]}]

set_property IOSTANDARD LVCMOS18 [get_ports {ssDisp[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ssDisp[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ssDisp[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ssDisp[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ssDisp[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ssDisp[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ssDisp[6]}]

set_property IOSTANDARD LVCMOS18 [get_ports reset]
set_property IOSTANDARD LVCMOS18 [get_ports clk]